config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    # collection, member are managed by the same controller
    collection do # collection porque no requiere un ID
      # top_restaurants GET    /restaurants/top(.:format)      restaurants#top
      get 'top'   # with collection we don't need->  , to: "restaurants#top", as: :top_restaurants
    end
    member do
      # chef_restaurant GET    /restaurants/:id/chef(.:format) restaurants#chef
      get 'chef'
    end

    # GET restaurants/:restauran_id/reviews/new  # Already in a restaurant, so just adding the path
    # POST restaurants/:restauran_id/reviews     #   restaurants/:restauran_id we get the ID
    # How can we do the below?
    resources :reviews, only: %i[new create]
    # restaurant_reviews POST   /restaurants/:restaurant_id/reviews(.:format)     reviews#create
    # new_restaurant_review GET    /restaurants/:restaurant_id/reviews/new(.:format) reviews#new
    # if [new create destroy]
    # restaurant_review DELETE /restaurants/:restaurant_id/reviews/:id(.:format) reviews#destroy
    # destroy requires "/restaurants/:restaurant_id" ? -> NO, only leopardice the path
    # so, destroy is generated outside resources :restaurants
  end
  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord         # has_many gives the collection -> restaurant.reviews
    has_many :reviews, dependent: :destroy   # When a restaurant deleted so its reviews must be deleted
end

app/models/review.rb
class Review < ApplicationRecord   # we require:  @review.restaurant = @restaurant
  belongs_to :restaurant  # It's already a validation, that is why in create of review_controller 
  validates :content, length: { minimum: 3 }
end                       # belongs_to gives the collection -> review.restaurant

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]
  before_action :find_restaurant, only: [:chef]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    # ID is required so chef it is added in before_action
    @chef_name = @restaurant.chef_name
  end

  private
    def find_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    # what happen if save doesn't work?, when review.save desn't save, the answer is =>false
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # With redirect_to reinicia todos los campos vuelve a empezar el request, para usar los
      # parámetros ya enviados se DEBE volver a usar
      # xxx redirect_to new_restaurant_review_path(@restaurant)
      render :new  # Asume se le pasa un Review.new, pero con parámetros, se queda en la misma acción
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy                                 # Although we DELETE the review from DB, 
    redirect_to restaurant_path(@review.restaurant) # we can access the deleted instance of that review
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- requerido por responsive, un marco de trabajo para apilar columnas o agrandar/reducir ventana -->
    <meta http-equiv="X-UA-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/chef.html.erb
<h1>El chef del <%= @restaurant.name%> es <%= @restaurant.chef_name %> </h1>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.rating %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>

<!-- new_restaurant_review GET    /restaurants/:restaurant_id/reviews/new(.:format) reviews#new  -->
<h2>Reviews. <small><%= link_to "Deja tu comentario", new_restaurant_review_path(@restaurant) %></small></h2>

<% @restaurant.reviews.each do |review| %>
  <p><%= review.content %>.
    <small>
      <%= link_to "Eliminar", review_path(review), method: :delete, data: { confirm: "Seguro?"}  %>
    </small>
  </p>
<% end %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/top.html.erb
<h1>Nuestros mejores restaurantes</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %><%= "*" * restaurant.rating %></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Agregar un comentario del restaurant <%= @restaurant.name %> </h1>


<%= simple_form_for [@restaurant, @review] do |form| %>   <!--form_for siguiendo convenciones sabe q ruta generar   -->  
  <!-- Just to show the errors internally saved in a log and replaced by
        "render :new" in reviews_controller.rb in create method
    <ul>
      <% if @review.errors.any? %>
        <% @review.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>      
    </ul> 
  -->
  <%= form.input :content, label: "Deja tu comentario" %>
  <%= form.button :submit %>
  <%= link_to 'Restaurant', restaurant_path(@restaurant) %>
<% end %>

<!-- form_for doesn't know about the route context, so it create the path: POST /reviews     ... -->
<!-- but, we need the path: POST restaurants/:restaurant_id/reviews  so we need to           ... -->
<!-- send the mother instance [@restaurant, @review] and form_for already knows about the ID ... -->